apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-index
  namespace: gox-nginx
data:
  index.html: |
    <html>
      <body style="font-family:Arial;text-align:center;margin-top:80px">
        <h1>GOX Sandbox</h1>
        <h2>GitOps Demo</h2>
        <p>Version 1</p>
      </body>
    </html>
