apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gox-nginx-demo
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/WasyeaG/gox-nginx-gitops-demo.git
    targetRevision: main
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: gox-nginx-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
